name: CICD for frontend

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master

      - run: npm install
        -
      - run: npm run build

      - name: Docker image build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: reshatsultan/hospital-frontend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}